apiVersion: v1
kind: Service
metadata:
  name: nagpaspmicroservice
  labels:
    run: nagpaspmicroservice
spec:
  selector:
    app: nagpaspmicroservice-pod
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer